basePath: /
definitions:
  handlers.ApiKeyResponse:
    properties:
      is_enabled:
        type: boolean
      key:
        type: string
      type:
        $ref: '#/definitions/models.ApiKeyType'
    type: object
  handlers.CreateAPIKeyRequest:
    properties:
      type:
        type: string
    required:
    - type
    type: object
  handlers.CreateShortLinkRequest:
    properties:
      filename:
        type: string
    required:
    - filename
    type: object
  models.ApiKeyType:
    enum:
    - upload
    - download
    - shorten
    - api
    type: string
    x-enum-varnames:
    - ApiKeyTypeUpload
    - ApiKeyTypeDownload
    - ApiKeyTypeShorten
    - ApiKeyTypeAPI
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a simple file sharing service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GoFi API
  version: "1.0"
paths:
  /{filename}:
    get:
      description: Downloads a file. Public files are accessible directly. For private
        files, a 'download' type token is required via query parameter or Authorization
        header.
      parameters:
      - description: Filename
        in: path
        name: filename
        required: true
        type: string
      - description: Authentication token for private files
        in: query
        name: token
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: The requested file
          schema:
            type: file
        "401":
          description: Unauthorized
          schema:
            properties:
              error:
                type: string
            type: object
        "403":
          description: Forbidden
          schema:
            properties:
              error:
                type: string
            type: object
        "404":
          description: Not Found
          schema:
            properties:
              error:
                type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Download a file
      tags:
      - Files
  /api-keys:
    post:
      consumes:
      - application/json
      description: Create a new API key. Requires an `api` type key.
      parameters:
      - description: API key information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateAPIKeyRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.ApiKeyResponse'
        "400":
          description: Bad Request
          schema:
            properties:
              error:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Create API key
      tags:
      - API Keys
  /api-keys/{key}:
    delete:
      description: Soft-disable an API key by setting its is_enabled flag to false.
      parameters:
      - description: API key value
        in: path
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            properties:
              message:
                type: string
            type: object
        "400":
          description: Bad Request
          schema:
            properties:
              error:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              error:
                type: string
            type: object
        "404":
          description: Not Found
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Disable API key
      tags:
      - API Keys
  /api-keys/{key}/enable:
    post:
      description: Enable an API key by setting its is_enabled flag to true.
      parameters:
      - description: API key value
        in: path
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            properties:
              message:
                type: string
            type: object
        "400":
          description: Bad Request
          schema:
            properties:
              error:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              error:
                type: string
            type: object
        "404":
          description: Not Found
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Enable API key
      tags:
      - API Keys
  /health:
    get:
      consumes:
      - '*/*'
      description: Show the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health Check
      tags:
      - Health
  /s/{shortcode}:
    get:
      description: Downloads a file using a short code. If the original file is private,
        a 'download' type token is required.
      parameters:
      - description: Short code of the file
        in: path
        name: shortcode
        required: true
        type: string
      - description: Authentication token for private files
        in: query
        name: token
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: The requested file
          schema:
            type: file
        "401":
          description: Unauthorized
          schema:
            properties:
              error:
                type: string
            type: object
        "404":
          description: Not Found
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      summary: Download a file from a short link
      tags:
      - Short Links
  /shorten:
    post:
      consumes:
      - application/json
      description: Creates a short link for an existing file. Requires a 'shorten'
        type token.
      parameters:
      - description: Request body containing the filename
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateShortLinkRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              short_url_path:
                type: string
            type: object
        "400":
          description: Bad Request
          schema:
            properties:
              error:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              error:
                type: string
            type: object
        "404":
          description: Not Found
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Create a short link
      tags:
      - Short Links
  /shorten/{shortcode}:
    delete:
      description: Soft-disable a short link by setting is_enabled to false
      parameters:
      - description: Short code of the file
        in: path
        name: shortcode
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            properties:
              message:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              error:
                type: string
            type: object
        "404":
          description: Not Found
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Disable short link
      tags:
      - Short Links
  /shorten/{shortcode}/enable:
    post:
      description: Reactivate a short link by setting is_enabled to true
      parameters:
      - description: Short code of the file
        in: path
        name: shortcode
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            properties:
              message:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              error:
                type: string
            type: object
        "404":
          description: Not Found
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Enable short link
      tags:
      - Short Links
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a file to either the public or private directory. Requires
        an 'upload' type token.
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      - description: 'Target directory: ''public'' or ''private'' (default)'
        enum:
        - public
        - private
        in: header
        name: X-GoFi-Target-Dir
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              download_path:
                type: string
            type: object
        "400":
          description: Bad Request
          schema:
            properties:
              error:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Upload a file
      tags:
      - Files
  /uuid:
    get:
      description: Return a random UUIDv4
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              uuid:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      summary: Generate a random UUIDv4
      tags:
      - Utility
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
